parser: "babel-eslint"
env:
    es6: true
    browser: true
    node: true
parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
        jsx: true
        experimentalObjectRestSpread: true
    sourceType: module
globals:
    afterAll: true
    afterEach: true
    beforeAll: true
    beforeEach: true
    describe: true
    test: true
    expect: true
plugins: [import]
extends:
    - plugin:import/recommended
rules:
    array-bracket-spacing: [error, never]
    eol-last: 0
    jsx-quotes: 1
    new-cap: 0
    no-debugger: 1
    no-undef: 2
    no-underscore-dangle: 0
    no-unused-vars: [error, {vars: all, args: none}]
    no-use-before-define: 0
    object-curly-spacing:  [error, never]
    quotes: [error, single, {avoidEscape: true, allowTemplateLiterals: true}]
    semi: [error, never]
    strict: 0
    import/no-named-as-default: 0
    import/unambiguous: 0
